-- AULA 2 DA FUNÇÂO CASE


SELECT P.NOME, 
	   DATEDIFF(YEAR, P.DATA_NASCIMENTO, GETDATE()) IDADE,
	   CASE WHEN (DATEDIFF(YEAR, P.DATA_NASCIMENTO, GETDATE())) BETWEEN 0 AND 18 THEN 'JOVEM'
			WHEN (DATEDIFF(YEAR, P.DATA_NASCIMENTO, GETDATE())) BETWEEN 19 AND 30 THEN ' JOVEM ADULTO'
			WHEN (DATEDIFF(YEAR, P.DATA_NASCIMENTO, GETDATE())) BETWEEN 31 AND 60 THEN 'ADULTO'
	   END FAIXA_ETARIA
FROM M2.PESSOAS P
ORDER BY 2 DESC