
--COPIA DA TABELA DE ITENS DE NOTA FISCAL

SELECT * INTO M1.ITEM_NOTA_FISCAL_COPIA FROM m1.ITEM_NOTA_FISCAL

DELETE FROM m1.ITEM_NOTA_FISCAL_COPIA WHERE ID_PRODUTO BETWEEN 200 AND 250


DELETE FROM m1.ITEM_NOTA_FISCAL_COPIA

--REMOVER UMA TABELA 
DROP TABLE m1.ITEM_NOTA_FISCAL_COPIA