
--CRIAÇÃO DE VIEW

CREATE OR ALTER VIEW vw_pessoa_Alterada AS
SELECT P.ID_PESSOA, P.NOME, P.ALTERADO_EM, P.ALTERADO_POR
FROM m2.PESSOAS P
WHERE P.ALTERADO_EM IS NOT NULL

GO


--USADA VIEWER
IF EXISTS (SELECT 1 FROM M2.PESSOAS WHERE ALTERADO_EM IS NOT NULL)
	SELECT * FROM vw_pessoa_Alterada
ELSE 
	PRINT 'NENHUMA PESSOA ALTERADA FOI ENCONTRADA...'