--Forma de pagamento
create table M1.FORMA_PAGAMENTO(
	ID_FORMA_PAGAMENTO NUMERIC(2,0) PRIMARY KEY,
	NOME_FORMA_PAGAMENTO NVARCHAR(100) NOT NULL,
	CADASTRADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
	CADASTRADO_POR CHAR(15) NOT NULL DEFAULT 'M1_DATADRIVEN',
	ATIVO BIT NOT NULL DEFAULT 0
)

CREATE TABLE M1.PESSOAS(
	ID_PESSOA NUMERIC(6,0) PRIMARY KEY,
	NOME NVARCHAR(250) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	GENERO CHAR (1),
	CPF NUMERIC(11,0) NOT NULL,
	RG NUMERIC(9,0),
	RG_DIGIT CHAR(1),
	CADASTRADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
	CADASTRADO_POR CHAR(15) NOT NULL DEFAULT 'M1_DATADRIVEN',
	ALTERADO_EM DATETIME,
	ALTERADO_POR CHAR(15)
)


-- TABELA NOTA FISCAL
CREATE TABLE M1.NOTA_FISCAL(
	FN_NUMERO NUMERIC (8,0) PRIMARY KEY,
	ID_PESSOA NUMERIC(6,0),
	ID_FORMA_PAGAMENTO NUMERIC(2,0) NOT NULL,
	VALOR_NOTA	NUMERIC(10,2)  NOT NULL,
	DATA_EMISSÃO DATETIME NOT NULL,
	DESCONTO NUMERIC (2,2) DEFAULT 0,
	FRETE BIT NOT NULL DEFAULT 0,
	CADASTRADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
	CADASTRADO_POR CHAR(15) NOT NULL DEFAULT 'M1_DATADRIVEN',
	ALTERADO_EM DATETIME,
	ALTERADO_POR CHAR(15)
)


CREATE TABLE M1.ENDERECOS(
	ID_ENDERECO NUMERIC (6,0) PRIMARY KEY,
	ID_PESSOA NUMERIC(6,0),
	ID_TIPO_ENDERECO NUMERIC(4,0) NOT NULL,
	ID_CIDADE NUMERIC(4,0) NOT NULL,
	ENDERECO NVARCHAR(255) NOT NULL,
	NUMERO NUMERIC (4,0) NOT NULL,
	COMPLEMENTO NVARCHAR(255),
	BAIRRO NVARCHAR(100),
	CADASTRADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
	CADASTRADO_POR CHAR(15) NOT NULL DEFAULT 'M1_DATADRIVEN',
	ALTERADO_EM DATETIME,
	ALTERADO_POR CHAR(15)
)


CREATE TABLE M1.ITEM_NOTA_FISCA(
	ID_PRODUTO NUMERIC (6, 0) NOT NULL,
	FN_NUMERO NUMERIC (8,0) NOT NULL,
	QUANTIDADE NUMERIC (6,0) NOT NULL,
	PRECO_UNITARIO NUMERIC (8,2) NOT NULL,
	CADASTRADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
	CADASTRADO_POR CHAR(15) NOT NULL DEFAULT 'M1_DATADRIVEN',
	ALTERADO_EM DATETIME,
	ALTERADO_POR CHAR(15)	
)


--CIDADES
CREATE TABLE M1.CIDADES(
    ID_CIDADE NUMERIC (4,0) PRIMARY KEY,
	ID_ESTADO NUMERIC (4,0) NOT NULL,
	CIDADE NVARCHAR (255) NOT NULL,
	CADASTRADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
	CADASTRADO_POR CHAR(15) NOT NULL DEFAULT 'M1_DATADRIVEN'
)



CREATE TABLE M1.TIPO_ENDERECO(
	ID_TIPO_ENDERECO NUMERIC(4,0) PRIMARY KEY,
	TIPO_ENDERECO NVARCHAR(50),
	CADASTRADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
	CADASTRADO_POR CHAR(15) NOT NULL DEFAULT 'M1_DATADRIVEN'
)

CREATE TABLE M1.PRODUTOS(
		ID_PRODUTO NUMERIC (6, 0) PRIMARY KEY,
		NOME_PRODUTO NVARCHAR (100) NOT NULL,
		VALOR_VENDA NUMERIC(8,2) NOT NULL,
		UNIDADE_VENDA NCHAR(10) NOT NULL,
		CADASTRADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
		CADASTRADO_POR CHAR(15) NOT NULL DEFAULT 'M1_DATADRIVEN',
		ALTERADO_EM DATETIME,
		ALTERADO_POR CHAR(15)	

)

CREATE TABLE M1.ESTADO(
	ID_ESTADO NUMERIC (4,0) PRIMARY KEY,
	ESTADO NCHAR (100) NOT NULL,
	CADASTRADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
	CADASTRADO_POR CHAR(15) NOT NULL DEFAULT 'M1_DATADRIVEN'
)