--DELETANDO PRODUTOS DO BANCO
DELETE FROM M1.PRODUTO 
WHERE ID_PRODUTO = 101


--NÃO FUNCIONA POIS OS PRODUTOS ESTÃO REFERENCIADOS NA TABELA ITEM DE NOTA FISCAL ENTÃO 
--É NECESSÁRIO APAGAR NA TABELA ITEM DE NOTA FISCAL PRIMEIRO PARA DEPOIS CONSEGUIR APARGAR NA TABELA DE PRODUTO

DELETE FROM M1.ITEM_NOTA_FISCAL 
WHERE ID_PRODUTO = 101