

-- FATURAMENTO POR CIDADE
select C.CIDADE, SUM(PRECO_UNITARIO) * SUM(QUANTIDADE) FATURAMENTO
from m1.ITEM_NOTA_FISCAL I 
INNER JOIN M1.NOTA_FISCAL N ON I.NF_NUMERO = N.NF_NUMERO
INNER JOIN M1.PESSOAS P ON P.ID_PESSOA = N.ID_PESSOA
INNER JOIN M1.ENDERECOS E ON E.ID_PESSOA = P.ID_PESSOA
INNER JOIN M1.CIDADES C ON C.ID_CIDADE = E.ID_CIDADE
GROUP BY C.CIDADE
