
--Função IF..ELSE (Condicional)

DECLARE @VALOR_A INT = 26,
		@VALOR_B INT = 25

IF @VALOR_A  < @VALOR_B
	SELECT 'A É MENOR QUE B...' -- TRUE
ELSE
	SELECT 'B É MAIOR QUE A...' -- FALSE


-- DIAS UTEIS E NÃO UTEIS
IF DATENAME(WEEKDAY, GETDATE()) IN ('SABADO', 'DOMINGO')
	PRINT('ESTAMOS EM UM ' + DATENAME(WEEKDAY, GETDATE()))
ELSE PRINT('ESTAMOS EM UM DIA DE SEMANA')