-- Funçoes  de texto: LEFT, RIGHT, LEN, REPLACE

--LEFT
-- EXTRAI A QUANTIDADE DE CARACTERES QUE EU DETERMINAR A ESQUERDA
SELECT LEFT('COMUNIDADE DATA DRIVEN', 10)

--EXTRAI AS 10 PRIMEIRAS POSIÇÕES DOS CARACTERES
-- E SUBSTITUE - REPLACE - ESPAÇOS POR TRAÇO 
SELECT LEFT(REPLACE(P.NOME,' ', '-'), 10) AS NOME 
FROM M2.PESSOAS P

--REPLACE
SELECT REPLACE(P.NOME,' ', '-') AS NOME_SEM_ESPACO
FROM M2.PESSOAS P


--RIGHT
--EXTRAI A QUANTIDADE DE CARACTERES QUE EU DETERMINAR A DIREITA
SELECT RIGHT('COMUNIDADE DATA DRIVEN', 6)

SELECT RIGHT( P.NOME, 10)
FROM M2.PESSOAS P


--LEN: QUANTIDADE DE CARACTERES EM UMA FRASE

SELECT LEN('COMUNIDADE DATA DRIVEN')

SELECT P.NOME NOME, LEN (P.NOME) [TAMANHO NOME]
FROM M2.PESSOAS P


-- NOME COM MAIOR QUANTIDADE DE LETRAS COM SUBQUERIES

SELECT MAX(X.[TAMANHO NOME])
FROM (
	SELECT P.NOME NOME, LEN (P.NOME) [TAMANHO NOME]
	FROM M2.PESSOAS P
)X

-- NOME COM MENOR QUANTIDADE DE LETRAS COM SUBQUERIES

SELECT MIN(X.[TAMANHO NOME])
FROM (
	SELECT P.NOME NOME, LEN (P.NOME) [TAMANHO NOME]
	FROM M2.PESSOAS P
)X

-- OU TAMBÉM PODE SER FEITO DESSA FORMA
--MIN
SELECT MIN(LEN(P.NOME)) TAMANHO_NOME
FROM M2.PESSOAS P

--MAX
SELECT MAX(LEN(P.NOME)) TAMANHO_NOME
FROM M2.PESSOAS P


