--INSERIDO DADOS NO BANCO USADO VARIAVEIS
declare @ID NUMERIC (4, 0)

SELECT @ID = MAX(ID_PRODUTO) + 1 FROM M1.PRODUTOS

INSERT INTO M1.PRODUTOS (ID_PRODUTO, NOME_PRODUTO, VALOR_VENDA, UNIDADE_VENDA) 
VALUES (@ID, CONCAT('PRODUTO', @ID),79.90, 'KG') 


--SELECT PARA CONFERIR SE A INSERÇÃO ESTA OK
SELECT * FROM M1.PRODUTOS
ORDER BY 5 DESC