--Listar os clientes que estão cadastrados mas não compraram
SELECT SUB.NOME, COUNT(1) QTD
FROM (
	SELECT P.ID_PESSOA ID, P.NOME, 'Pessoa' ORIGEM 
	FROM m2.PESSOAS P

	union all

	SELECT NF.ID_PESSOA ID, P.NOME, 'Cliente NF' ORIGEM
	FROM M2.NOTA_FISCAL NF
	INNER JOIN M2.PESSOAS P ON P.ID_PESSOA = NF.ID_PESSOA
) SUB
GROUP BY SUB.NOME
HAVING COUNT(1) = 1