--Segunda aula de funções de texto
-- LOWER, UPPER, RTRIM, SUBSTRING

-- LOWER: DEIXA AS LETRAS MINUSCULAS
SELECT *, LOWER(CADASTRADO_POR)CADASTRADO_POR_MINUSCULO
FROM m2.PESSOAS

-- UPPER DEIXA AS LETRAS MAIUNSCULAS
SELECT *, UPPER(NOME)NOME_MAIUSCULO
FROM m2.PESSOAS

--LTRIN: REMOVE OS ESPAÇOS A ESQUERDA
SELECT LTRIM('   COMUNIDADE DATADRIVEM') TEXTO

--RTRIM: REMOVE OS ESPAÇOS A DIREITA
SELECT RTRIM('COMUNIDADE DATADRIVEM   ') TEXTO