-- Listar notas cuja forma de pagamento seja dinheiro ou cartão de debito

SELECT NF.NF_NUMERO, NF.VALOR_NOTA, FORMAT(NF.DATA_EMISSÃO,'dd/MM/yyyy') DATA
FROM m2.NOTA_FISCAL NF
WHERE NF.ID_FORMA_PAGAMENTO IN (
	SELECT FP.ID_FORMA_PAGAMENTO
	FROM m2.FORMA_PAGAMENTO FP
	WHERE FP.NOME_FORMA_PAGAMENTO IN ('DINHEIRO','CARTÃO DE DÉBITO')
)


--TOTALIZAR
SELECT FORMAT(SUM(SUB.VALOR_NOTA),'C','pt-BR') MONTANTE_TOTAL
FROM (
	SELECT NF.NF_NUMERO, NF.VALOR_NOTA, FORMAT(NF.DATA_EMISSÃO,'dd/MM/yyyy') DATA
	FROM m2.NOTA_FISCAL NF
	WHERE NF.ID_FORMA_PAGAMENTO IN (
		SELECT FP.ID_FORMA_PAGAMENTO
		FROM m2.FORMA_PAGAMENTO FP
		WHERE FP.NOME_FORMA_PAGAMENTO IN ('DINHEIRO','CARTÃO DE DÉBITO')
	)
)SUB