
--Total de vendas por estados
SELECT SUB.ESTADO, SUM(SUB.VL_NF) TOTAL
FROM (
	select NF.VALOR_NOTA VL_NF, EST.ESTADO
	from m2.NOTA_FISCAL NF 
		LEFT JOIN m2.PESSOAS P on NF.ID_PESSOA = P.ID_PESSOA
		LEFT JOIN m2.ENDERECOS E ON E.ID_PESSOA = P.ID_PESSOA AND E.ID_TIPO_ENDERECO = 1
		LEFT JOIN M2.CIDADES C ON C.ID_CIDADE = E.ID_CIDADE 
		LEFT JOIN M2.ESTADO EST ON EST.ID_ESTADO = C.ID_ESTADO
	) SUB
GROUP BY SUB.ESTADO